## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Ribeira Grande,PT,38.52,-28.70,60.80,77,40,13.87,scattered clouds
1,1,Butaritari,KI,3.07,172.79,81.25,76,94,15.84,overcast clouds
2,2,Virginia Beach,US,36.85,-75.98,72.00,73,75,4.70,broken clouds
3,3,Nakhon Thai,TH,17.10,100.84,72.10,86,0,3.00,clear sky
4,4,Dubuque,US,42.48,-90.87,71.01,44,7,8.01,clear sky

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp).dropna() & \
                                       (city_data_df["Max Temp"] >= min_temp).dropna()]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Butaritari,KI,3.07,172.79,81.25,76,94,15.84,overcast clouds
7,7,Puerto Ayora,EC,-0.74,-90.35,75.20,73,75,12.75,broken clouds
9,9,Vila Velha,BR,-20.33,-40.29,79.00,74,40,16.11,scattered clouds
11,11,Gouyave,GD,12.16,-61.73,86.00,79,75,19.46,broken clouds
16,16,Zacualpan,MX,21.25,-105.17,80.60,42,5,11.41,clear sky
24,24,Sao Joao Da Barra,BR,-21.64,-41.05,75.20,69,90,10.29,overcast clouds
32,32,Sinnamary,GF,5.38,-52.95,81.84,83,38,7.83,moderate rain
39,39,Salalah,OM,17.02,54.09,78.80,61,0,2.24,clear sky
40,40,San Andres,CO,12.58,-81.70,78.80,94,75,11.41,light intensity drizzle
43,43,Mabaruma,GY,8.20,-59.78,81.99,88,47,5.48,moderate rain

In [7]:
# 4a. Determine if there are any empty rows.
#Look at Module 4.5.1
preferred_cities_df.isnull().sum

<bound method DataFrame.sum of      City_ID   City  Country    Lat    Lng  Max Temp  Humidity  Cloudiness  \
1      False  False    False  False  False     False     False       False
7      False  False    False  False  False     False     False       False
9      False  False    False  False  False     False     False       False
11     False  False    False  False  False     False     False       False
16     False  False    False  False  False     False     False       False
..       ...    ...      ...    ...    ...       ...       ...         ...
666    False  False    False  False  False     False     False       False
667    False  False    False  False  False     False     False       False
668    False  False    False  False  False     False     False       False
679    False  False    False  False  False     False     False       False
682    False  False    False  False  False     False     False       False

     Wind Speed  Current Description
1         False                False
7         False                False
9         False                False
11        False                False
16        False                False
..          ...                  ...
666       False                False
667       False                False
668       False                False
679       False                False
682       False                False

[184 rows x 10 columns]>

In [8]:
# 4a. Determine if there are any empty rows.
#Look at Module 4.5.1
city_data_df.isnull().sum

<bound method DataFrame.sum of      City_ID   City  Country    Lat    Lng  Max Temp  Humidity  Cloudiness  \
0      False  False    False  False  False     False     False       False
1      False  False    False  False  False     False     False       False
2      False  False    False  False  False     False     False       False
3      False  False    False  False  False     False     False       False
4      False  False    False  False  False     False     False       False
..       ...    ...      ...    ...    ...       ...       ...         ...
679    False  False    False  False  False     False     False       False
680    False  False    False  False  False     False     False       False
681    False  False    False  False  False     False     False       False
682    False  False    False  False  False     False     False       False
683    False  False    False  False  False     False     False       False

     Wind Speed  Current Description
0         False                False
1         False                False
2         False                False
3         False                False
4         False                False
..          ...                  ...
679       False                False
680       False                False
681       False                False
682       False                False
683       False                False

[684 rows x 10 columns]>

In [9]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
hotel_df = preferred_cities_df.dropna()

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
clean_hotel_df = hotel_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
clean_hotel_df["Hotel Name"] = ""
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Butaritari,KI,81.25,overcast clouds,3.07,172.79,
7,Puerto Ayora,EC,75.20,broken clouds,-0.74,-90.35,
9,Vila Velha,BR,79.00,scattered clouds,-20.33,-40.29,
11,Gouyave,GD,86.00,broken clouds,12.16,-61.73,
16,Zacualpan,MX,80.60,clear sky,21.25,-105.17,
24,Sao Joao Da Barra,BR,75.20,overcast clouds,-21.64,-41.05,
32,Sinnamary,GF,81.84,moderate rain,5.38,-52.95,
39,Salalah,OM,78.80,clear sky,17.02,54.09,
40,San Andres,CO,78.80,light intensity drizzle,12.58,-81.70,
43,Mabaruma,GY,81.99,moderate rain,8.20,-59.78,

In [11]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        clean_hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    #except Exception as ex: 
        #print(ex)
    except (IndexError):
        print("Hotel not found... skipping.")
clean_hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Butaritari,KI,81.25,overcast clouds,3.07,172.79,Isles Sunset Lodge
7,Puerto Ayora,EC,75.20,broken clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
9,Vila Velha,BR,79.00,scattered clouds,-20.33,-40.29,Hotel Vitória Palace
11,Gouyave,GD,86.00,broken clouds,12.16,-61.73,Rumboat Retreat
16,Zacualpan,MX,80.60,clear sky,21.25,-105.17,La Colorada B&B
24,Sao Joao Da Barra,BR,75.20,overcast clouds,-21.64,-41.05,Pousada Porto De Canoas
32,Sinnamary,GF,81.84,moderate rain,5.38,-52.95,ALETHEIA Appartement Sinnamary
39,Salalah,OM,78.80,clear sky,17.02,54.09,HAMDAN PLAZA HOTEL
40,San Andres,CO,78.80,light intensity drizzle,12.58,-81.70,Hotel Arena Blanca
43,Mabaruma,GY,81.99,moderate rain,8.20,-59.78,

In [12]:
# 7. Drop the rows where there is no Hotel Name.
#boolean masking
clean_hotel_df = clean_hotel_df[clean_hotel_df["Hotel Name"] != ""]
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Butaritari,KI,81.25,overcast clouds,3.07,172.79,Isles Sunset Lodge
7,Puerto Ayora,EC,75.20,broken clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
9,Vila Velha,BR,79.00,scattered clouds,-20.33,-40.29,Hotel Vitória Palace
11,Gouyave,GD,86.00,broken clouds,12.16,-61.73,Rumboat Retreat
16,Zacualpan,MX,80.60,clear sky,21.25,-105.17,La Colorada B&B
24,Sao Joao Da Barra,BR,75.20,overcast clouds,-21.64,-41.05,Pousada Porto De Canoas
32,Sinnamary,GF,81.84,moderate rain,5.38,-52.95,ALETHEIA Appartement Sinnamary
39,Salalah,OM,78.80,clear sky,17.02,54.09,HAMDAN PLAZA HOTEL
40,San Andres,CO,78.80,light intensity drizzle,12.58,-81.70,Hotel Arena Blanca
46,Axim,GH,79.83,broken clouds,4.87,-2.24,AXIM BEACH RESORT AND SPA

In [13]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [18]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd> 
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [19]:
# 11a. Add a marker layer for each city to the map. 
locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))